### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ozky** [M4rtinK/monav-light#1]
I got errors when i try to build program i post error log in file.
[file.txt](https://github.com/M4rtinK/monav-light/files/158657/file.txt)

**Comment by M4rtinK** [comment]
I'm getting the same error message when trying to build monav-light with GCC 5.3.1 on Fedora 23. Could be that the newer GCC no longer accepts the monav-light source code as valid.

Will investigate. :)

**Comment by ozky** [comment]
It still fails to build even cloned fixed master branch same error.

**Comment by yarda** [comment]
I am unable to reproduce the build failure.
qt-5.5.1
gcc-5.3.1

ozky: What's your gcc and qt version? Could you try to build from fresh checkout?

**Comment by ozky** [comment]
Qt 5.4 and gcc 5.3.1 gcc is updated manually to new version,i just tested this works with qt 5.5 and gcc 5.3.1 not with Mageia 5 qt 5.4 gcc 4.9.

**Comment by yarda** [comment]
I am unable to reproduce the problem. I re-tried with:
qt-5.4.1
gcc-4.9.2
It was a bit tricky to downgrade f23 box to these versions, but it still compiles OK and there are no warnings. I compiled with "-Wall -Werror=format-security".

The format-security error probably doesn't trigger because there cannot be passed anything else than string literals into qcritical. Maybe your gcc just used more simple/naive check. I am just guessing, but the fix should be simple.

**Comment by yarda** [comment]
@ozky does it work for you now?

**Comment by ozky** [comment]
Yes now it's working with -Wall -Werror=format-security.
